# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries: "*"
    labels: [ "version update" ]
    groups:
      kotlin-ksp-compose:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.jvm"
          - "com.google.devtools.ksp"
          - "com.google.devtools.ksp.gradle.plugin"
          - "androidx.compose.compiler:compiler"
      gradle-plugin-and-build-tools:
        patterns:
          - "com.android.tools:common"
          - "com.android.tools.build:gradle"
          - "com.android.application"
          - "com.android.library"
          - "com.android.test"
registries:
  maven-google:
    type: "maven-repository"
    url: "https://maven.google.com"
    replaces-base: true
